transforms:
  size:
    - 256
    - 512
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  num_classes: 21

data_preparation:
  root: data/cityscapes
  img_folder_name: img
  label_folder_name: label

data_loader:
  batch_size: 4
  num_workers: 2
  pin_memory: true

attentionUNet_model:
  in_channels: 3
  base_channels: 64
  upsample_size: [256, 512]

model:
  model_name: AttentionUNet
  num_classes: 21

model_trainer:
  model_name: AttentionUNet
  num_epochs: 10
  batch_size: 4
  learning_rate: 1e-4
  num_classes: 21

metric_logger:
  model_name: AttentionUNet
